[workspace]
members = [
    "crates/ids-core",
    "crates/ids-cli",
    "crates/ids-py",
    "crates/ids-covariates",
]

# Set the resolver to version 2 as recommended
resolver = "2"

# Set workspace-wide configuration
[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Tobias Kragholm <tkragholm@gmail.com>"]
description = "Incidence Density Sampling implementation in Rust"


# Define shared development dependencies
[workspace.dependencies]
log = "0.4"
env_logger = "0.10"
chrono = { version = "0.4", features = ["serde"] }
csv = "1.2"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0.11"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = 3
