[workspace]
members = [
    "crates/core",
    "crates/cli",
    "crates/py",
    "crates/covariates",
    "crates/loader",
    "crates/types", "crates/datagen",
]

# Set the resolver to version 2 as recommended
resolver = "2"

# Set workspace-wide configuration
[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Tobias Kragholm <tkragholm@gmail.com>"]
description = "Incidence Density Sampling implementation in Rust"


# Define shared development dependencies
[workspace.dependencies]
log = "0.4"
env_logger = "0.10"
chrono = { version = "0.4", features = ["serde"] }
csv = "1.2"
serde = { version = "1.0", features = ["derive"] }
arrow = { version = "54.1.0", features = ["prettyprint"] }
arrow-array = "54.1.0"
arrow-schema = "54.1.0"
arrow-select = "54.1.0"
parquet = { version = "54.1.0", features = ["arrow"] }
thiserror = "2.0.11"
rayon = "1.10.0"
clap = { version = "4.5", features = ["derive"] }
log4rs = { version = "1.2", features = ["console_appender"] }
dashmap = "6.1.0"
statrs = "0.18"
rand = "0.8.5"
smallvec = "1.13.2"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = 3
