[package]
name = "icd-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bit-vec = "0.8.0"
chrono = { version = "0.4.39", features = ["serde"] }
colored = "3.0.0"
csv = "1.3.1"
dashmap = "6.1.0"
fastrand = "2.3.0"
hashbrown = "0.15.2"
humantime = "2.1.0"
indicatif = "0.17.11"
mimalloc = "0.1.43"
ndarray = { version = "0.16.1", features = ["rayon"] }
parking_lot = "0.12.3"
plotters = "0.3.7"
rand = "0.9.0"
rand_distr = "0.5.0"
rayon = "1.10.0"
rustc-hash = "2.1.1"
serde = { version = "1.0.217", features = ["derive"] }
smallvec = "1.13.2"
thiserror = "2.0.11"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = 3
