[package]
name = "types"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
chrono.workspace = true
serde.workspace = true
csv.workspace = true
thiserror.workspace = true
arrow.workspace = true
arrow-array.workspace = true
arrow-schema.workspace = true
arrow-select.workspace = true
parquet.workspace = true
dashmap.workspace = true
rand.workspace = true
log.workspace = true
serde_json.workspace = true
hashbrown.workspace = true
polars = { version = "0.46.0", features = ["lazy", "parquet", "dtype-date", "strings", "performant", "temporal"], optional = true }
polars-arrow = { version = "0.46.0", optional = true }
num_cpus = { version = "1.16.0", optional = true }

[features]
default = []
polars_backend = ["polars", "polars-arrow", "num_cpus"]
